name: Build and Scan

on:
  pull_request:
  workflow_dispatch:

jobs:
  build-and-scan:
    runs-on: ubuntu-latest

    steps:
      # This step checks out a copy of your repository.
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Build Docker image
        run: |
          docker build -t myregistry/my-vuln-application:latest .

      - name: Scan my-vuln-application
        id: scan
        uses: sysdiglabs/scan-action@v5
        with:
          # Tag of the image to analyse
          image-tag: myregistry/my-vuln-application:latest
          # API token for Sysdig Scanning auth
          sysdig-secure-url: https://us2.app.sysdig.com/secure
          sysdig-secure-token: ${{ secrets.KUBELAB_SECURE_API_TOKEN }}
          stop-on-failed-policy-eval: true
          stop-on-processing-error: true


      - name: Upload SARIF file
        if: success() || failure() # Upload results regardless previous step fails
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: ${{ github.workspace }}/sarif.json

      - name: Push to registry
        run: |
          docker push myregistry/my-vuln-application:latest
